### PR TITLE
Basic Algorithms

### PR DESCRIPTION
**Pull request by 18-Ritika**

### CODE REVIEW

**Review by shreyanshdeep — APPROVED** [review]

**Comment by shreyanshdeep** [comment]
Hey @18-Ritika , please make changes to the readme file.

**Comment by 18-Ritika** [comment]
i have deleted the readme .

**Comment by Rishabhkapoor** [comment]
@18-Ritika , the branch still has conflicts. Please make changes to your README.md file

**Comment by 18-Ritika** [comment]
what change exactly I have to do .?

**Pull request closed without merging**
