### PR TITLE
Added kadane's algorithm.cpp By zahinekbal

### PR DESCRIPTION
**Pull request by zahinekbal**
I Updated my code file Kadane's algorithm.cpp for maximum- subarray-sum in basic_algorithm folder with Explanation , Algorithms ,Example & Implementation.
kindly check my code & review my PR.....

### CODE REVIEW

**Comment by Rishabhkapoor** [comment]
Hey @zahinekbal , Please create an issue before making a PR or mention the issue for which you are making the PR. You can make use of the template we have created for the same.

**Comment by zahinekbal** [comment]
@Rishabhkapoor so before making PR I have to write here what m I gonna do ...right?

**Comment by zahinekbal** [comment]
@Rishabhkapoor please help me I wanna add 
Kadane's algorithm nd bubble sorting in C++ STL
What I hv to do before making PR...

**Comment by zahinekbal** [comment]
Screenshot (16)
You are talking about this..

**Comment by zahinekbal** [comment]
@Rishabhkapoor So In column section I have to fill add my algorithms name right ?

**Comment by Rishabhkapoor** [comment]
yes

**Comment by zahinekbal** [comment]
Screenshot (17)
@Rishabhkapoor but here what i have to do i am not understanding can you please tell me

**Comment by Rishabhkapoor** [comment]
First You need to create an issue and then you can make a PR and link it to the issue that u have made.

**Comment by Rishabhkapoor** [comment]
@zahinekbal, you can use add-new-algorithm.md

**Comment by zahinekbal** [comment]
@Rishabhkapoor So if i create issue then no need to fill this file (add-new-algorithm.md)  right? 
or else i can only update add-new-algorithm.md...
Am i correct?

**Comment by zahinekbal** [comment]
please reply

**Comment by Rishabhkapoor** [comment]
You need to create an issue.

**Comment by zahinekbal** [comment]
@Rishabhkapoor See i create issue what i have to do now tell please.....

**Comment by zahinekbal** [comment]
How can i assigned to me ? beacuse everyone is commenting for assigning

**Comment by zahinekbal** [comment]
@Rishabhkapoor  I created an issue (#204 (Kadane's Algorithm)) And i updated my code
please check it and review my PR.

**Pull request closed without merging**
