### PR TITLE
Created N-queen-problem.cpp

### PR DESCRIPTION
**Pull request by akshitagupta15june**
added in a backtracking folder.
please merge this pr.

### CODE REVIEW

**Comment by shreyanshdeep** [comment]
Please create an issue before making a PR. You can make use of the template we have created for the same.

**Comment by akshitagupta15june** [comment]
ok i am creating an issue @shreyanshdeep

**Comment by akshitagupta15june** [comment]
@shreyanshdeep #303 please see the pr and the issue

**Comment by akshitagupta15june** [comment]
Duplicate of #303

**Pull request closed without merging**
