### PR TITLE
Added Linked Lists Folder with 2 Questions

### PR DESCRIPTION
**Pull request by shikhar8434**

### CODE REVIEW

**Comment by Rishabhkapoor** [comment]
Hey @shikhar8434, Add comments in your program

**Review by Rishabhkapoor — CHANGES_REQUESTED** [review]
Hey @shikhar8434, Add comments in your program

**Comment by shikhar8434** [comment]
Okay

**Comment by shikhar8434** [comment]
Done ! Kindly merge it

**Comment by shikhar8434** [comment]
@Rishabhkapoor

**Review by Rishabhkapoor — APPROVED** [review]

**Review by shreyanshdeep — APPROVED** [review]

**Pull request merged**
