### PR TITLE
Create LinkedListBasicFunctions.c

### PR DESCRIPTION
**Pull request by Kirtiahuja**
basic linked list functions

### CODE REVIEW

**Comment by Rishabhkapoor** [comment]
Hey @Kirtiahuja , Please create an issue before making a PR or link the issue for which you are making the PR. You can make use of the template we have created for the same.

**Comment by Kirtiahuja** [comment]
Issue no. #242 just check

**Comment by Kirtiahuja** [comment]
Made a program on the issue number #242

**Review by Kirtiahuja — COMMENTED** [review]
added comments

**Comment by shreyanshdeep** [comment]
Hey @Kirtiahuja , please add this code inside the linked list folder. ;)

**Pull request closed without merging**
