### PR TITLE
Added Z and Manachar's Algorithms

### PR DESCRIPTION
**Pull request by H4R5H1T-007**
#191 
Addition of Z and Manachar's algorithms.

### CODE REVIEW

**Comment by Rishabhkapoor** [comment]
Hey @H4R5H1T-007 , add more comments to your program

**Comment by H4R5H1T-007** [comment]
ok.

**Comment by H4R5H1T-007** [comment]
Done adding comments. Now can you check it and see if there is any more things needed to change??

**Comment by H4R5H1T-007** [comment]
@Rishabhkapoor Done adding comments. Now can you check it and see if there is any more things needed to change??

**Comment by H4R5H1T-007** [comment]
Hey @Rishabhkapoor , Please Check the codes and reply.

**Review by shreyanshdeep — APPROVED** [review]

**Pull request merged**
