### PR TITLE
Added Russian Peasant Algorithm

### PR DESCRIPTION
**Pull request by mahimagoyalx**

### CODE REVIEW

**Comment by shreyanshdeep** [comment]
Please create an issue before making a PR. You can make use of the template we have created for the same.

**Comment by mahimagoyalx** [comment]
Hey, I am really sorry, I have raised the issue #130, please reopen this pull request again. @shreyanshdeep

**Review by shreyanshdeep — APPROVED** [review]

**Comment by mahimagoyalx** [comment]
Thank you for the approval, could you please also remove the invalid tag? @shreyanshdeep

**Comment by mahimagoyalx** [comment]
Please remove the invalid label. @shreyanshdeep

**Comment by mahimagoyalx** [comment]
@ayush0x00 This PR has been merged, please remove the invalid tag.

**Pull request merged**
