### PR TITLE
CombSort implementation in Java

### PR DESCRIPTION
**Pull request by plaidshirtakos**
Set of numbers are read from keyboard.

### CODE REVIEW

**Comment by ayush0x00** [comment]
@plaidshirtakos please add some comment as to what the algorithm intends to solve.

**Comment by plaidshirtakos** [comment]
@ayush0x00 : combSort() function implements the sorting algorithm, which takes array of integers(typed in numbers) as parameter value.

Comb Sort is an improvement of classic bubble sort. Items are sorted in a specific gap. After completing each phase, the gap is decreased. The decreasing factor or the shrink factor for this sort is 1.3. It means that after completing each phase the gap is divided by 1.3.

**Review by Rishabhkapoor — CHANGES_REQUESTED** [review]
@plaidshirtakos , Add this comment in your program, not here

**Comment by plaidshirtakos** [comment]
@Rishabhkapoor : Thanks, I edited it.

**Review by shreyanshdeep — APPROVED** [review]

**Pull request merged**
