### PR TITLE
added Brian Kernighan's Algorithm,updated readme.md

### PR DESCRIPTION
**Pull request by pathak-abhinav**
added under issue created as "Add new algorithm for Bit Manipulation".
Please review and let me know.

### CODE REVIEW

**Review by surya7765 — APPROVED** [review]

**Comment by pathak-abhinav** [comment]
Please review the new PR,#219 and Issue created.

**Comment by Rishabhkapoor** [comment]
Hey @absum11 , Please create an issue before making a PR or link the issue for which you are making the PR. You can make use of the template we have created for the same.

**Comment by pathak-abhinav** [comment]
An issue has already been created by me named "add algorithms for bit Manipulation"#218, I think You didn't check that.

**Comment by Rishabhkapoor** [comment]
You need to **LINK** the issue to this PR; along with writing the issue number, u need to write Fixes. So that your PR can close the issue that you have created.

**Comment by pathak-abhinav** [comment]
Sorry for the mistake, Since it is the first time, I created an issue so I was unaware of this supported keyword feature for linking a PR to an issue. I will try to be accurate this time.

**Pull request closed without merging**
