### PR TITLE
String program added to reverse words

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Rishabhkapoor** [comment]
Hey @06rakshitha , Please create an issue before making a PR. You can make use of the template we have created for the same.

**Comment by 06rakshitha** [comment]
Open this pull request once. Please let me revert this pull request.
Thank you.

**Comment by 06rakshitha** [comment]
Hey I just created an issue.

**Comment by 06rakshitha** [comment]
Can you please check now. The solution is in this pr. Please let me know what other changes I'll have to follow.
Thank you!

**Pull request closed without merging**
